# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.
name: Release to latest/edge

on:
  push:
    branches:
      - main

jobs:
  ci-tests:
    name: Tests
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  build:
    name: Build charm
    needs:
      - ci-tests
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v29.1.0

  release-libs:
    name: Release bumped library
    runs-on: ubuntu-24.04
    needs:
      - ci-tests
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Release bumped charm library
        uses: canonical/charming-actions/release-libraries@2.6.3
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  release:
    name: Release charm
    needs:
      - ci-tests
      - build
    uses: canonical/data-platform-workflows/.github/workflows/release_charm.yaml@v29.1.0
    with:
      channel: latest/edge
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
    secrets:
      charmhub-token: ${{ secrets.CHARMHUB_TOKEN }}
    permissions:
      contents: write  # Needed to create GitHub release
